services:
  - type: web
    name: marmelo-kitchen-portal
    env: node
    plan: free
    branch: main
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: ~18.0.0
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_PORT
        sync: false
